apiVersion: v1
kind: Service
metadata:
  name: prufwerk
  labels:
    app: prufwerk
spec:
  selector:
    app: prufwerk
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
